import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { api } from '../utils/api';
import Image from 'next/image';
import { ChangeEvent, useState } from 'react';

const Home: NextPage = () => {
  const [input, setInput] = useState('');
  const greeting = api.hauni.greeting.useQuery({ text: 'Hauninator' });
  const url = api.hauni.picture.useQuery();

  const openAi = api.hauni.openai.useQuery({ query: input });

  const setData = (element: HTMLInputElement) => {
    const debounce = setTimeout(() => setInput(element.value), 5000);
    return () => clearTimeout(debounce);
  };

  return (
    <>
      <Head>
        <title>Hauninator </title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Image
          src={url.data?.link ? url.data.link : 'Loading picture'}
          alt='hauni'
          width={200}
        />
        <p className={styles.showcaseText}>
          {greeting.data ? greeting.data.greeting : 'Loading tRPC query...'}
        </p>
        <input
          type={'text'}
          placeholder='Type in requests'
          onChange={(e: ChangeEvent<HTMLInputElement>) => setData(e.target)}
          className='form__field'
        />
        <p className={styles.showcaseText} style={{ width: '60%' }}>
          {openAi.data && input ? openAi.data.text : '...'}
        </p>
      </main>
    </>
  );
};

export default Home;
